### ISSUE TITLE
Application failed to start due to no Qt platform plugin could be initialized??

### ISSUE THREAD

**Issue by TiekHan** [RfidResearchGroup/proxmark3#1274]
I encounter this issue for both the proxmark3 command line, and the universal gui. Strangely the cross-compiled gui doesnt have this kind of problem. Any idea how to fix this? Thanks.
![Screenshot 2021-05-15 210631](https://user-images.githubusercontent.com/19300854/118362396-f776b680-b5c1-11eb-8c4f-46e266c512f8.png)
![Screenshot 2021-05-15 210709](https://user-images.githubusercontent.com/19300854/118362400-fa71a700-b5c1-11eb-8bb4-5a663efe3263.png)

**One more thing, the pm3.bat is working fine for me.**
![Screenshot 2021-05-15 211404](https://user-images.githubusercontent.com/19300854/118362581-956a8100-b5c2-11eb-99eb-6740f15e4627.png)

**Comment by iceman1001** [comment]
When it comes to the GUI,  we don't support other software in this repo.  
When it comes to pre-compiled binaries,  same thing, we don't support it in this repo.  You have to ask @Gator96100  nicely.

And since the last image shows it to be working,   then there seem _not_ to be any problem with this repo.  

If you don't show relevant information to this repo, I will close this issue

**Comment by TiekHan** [comment]
alright, let me figure out what caused this . Thanks @iceman1001

**Comment by Gator96100** [comment]
The reason pm3.bat works is because it calls setup.bat. 
Hint: look at what variables are sets by setup.bat

**Comment by TiekHan** [comment]
Thanks @Gator96100 , i managed to make it works by adding a system variable = "QT_QPA_PLATFORM_PLUGIN_PATH" , variable value = "%QT_PLUGIN_PATH%".
