### ISSUE TITLE
Segfault when calling pm3 from Lua (experimental_lib)

### ISSUE THREAD

**Issue by doegox** [RfidResearchGroup/proxmark3#2594]
Quick notes not to forget:

```
$ cd client/experimental_lib
$ ./01make_lib.sh
$ cd example_lua
$ ./01link_lib.sh
$ ./02run_test.sh
[=] Session log /home/phil/.proxmark3/logs/log_20241027110937.txt
[+] Using UART port /dev/ttyACM0
[+] Communicating with PM3 over USB-CDC
Segmentation fault
```

Problem appeared somewhere when Lua got migrated from 5.2 to 5.4:
![image](https://github.com/user-attachments/assets/28818f90-1e1d-430e-bacc-c298845baa60)

but to test these old commits, one has to add the missing line
`${PM3_ROOT}/client/src/lua_bitlib.c`
in `client/experimental_lib/CMakeLists.txt` as done later with 50d9042a5cd5415dce0c54ad077529f12cbee108

**Comment by doegox** [comment]
@jmichelp could you have a look please?

**Comment by jmichelp** [comment]
Just had a go at testing. Works for me after a few tweaks due to OSX:
- had to enforce SKIPQT=1 in the build script otherwise compilation fails (probably some missing CFLAGS as the pre-processor complains about c++17 standard being required)
- had to manually symlink `pm3.so` because the build library is `.dylib` on OSX
- had to also symlink `dkjson.lua` to run the second test in the example otherwise the Lua module wasn't found.

No segfault.

Will test on a Linux next.

**Comment by jmichelp** [comment]
Same behavior on Linux after an extra `ln -sf ../../lualibs/dkjson.lua .` to run the tests until the end

**Comment by jmichelp** [comment]
Considering that the example relies on the system `lua` binary, my current assumption would be that client and libraries were compiled against the bundled lua5.4 library but you're trying to run the script using your system `lua.5.2` interpreter. The bytecode will be different and would result in a segv.

I could confirm this behavior on my Linux machine by running:
```bash
$ sudo apt remove lua5.4
$ sudo apt install lua5.2
$ ./02run_test.sh
[...]
[+] Communicating with PM3 over USB-CDC
./02run_test.sh: line 8: 2957012 Segmentation fault      ./test.lua
```

**Comment by doegox** [comment]
😮🤦‍♂️ that makes totally sense, thanks!
I pushed a fix to call lua5.4 in the shebang and added the dkjson symlink
