### ISSUE TITLE
Keri MS Clone with FC and ID

### ISSUE THREAD

**Issue by mwalker33** [RfidResearchGroup/proxmark3#616]
Drafting the code to allow a keri MS clone and supporting the FC and ID

As is :  lf keri clone <internal id> <q5>

Looking for feed back on how you would like the command to be formatted.
in my test code i have
lf keri clone m <fc> <id>
where m = ms. 
if the 'm' option is not supplied it will default back to the current internal id.

Given that we my have other formats in the future would it be better with something like...
lf keri clone t <ms|other types|...> f <fc> i <id> [q5]
and a fallback if no "t" option to the current clone from internal id.
i.e. lf keri clone <internal id> [q5] 

How would you like the command to work ?

Optioned/extended format
```
clone a KERI tag to a T55x7 tag.
Usage: lf keri clone [h] <id> <Q5>
Usage extended: lf keri clone [h] t <m|i> [f <fc>] i <id> [Q5]
Options:
      h          : This help
      <id>       : Keri Internal ID
      <Q5>       : specify write to Q5 (t5555 instead of t55x7)
      <t> [m|i]  : Type. m - MS, i - Internal ID
      <f> <fc>   : Facility Code
      <i> <id>   : Card ID

Examples:
       lf keri clone 112233
       lf keri clone type ms fc 6 id 12345
       lf keri clone t m f 6 i 12345
```
Happy to rework as needed.

**Comment by iceman1001** [comment]
lets see.    To make sure we gonna get a unify among all lf commands,
when it comes to different types,  I starting to like   MS/INTERNAL  ie long params instead of  1 = ms, 2 = internal.    Where the latter has been used everywhere before but its utterly confusing to keep track of what a 1 means across the commands because of it.

And when using long params,  I tend to convert to str_lower first and then str_startswith,  instead of having at full correct name.   It enables   MS/IN  or ms/in as valid inputs and accepts ms/internal aswell.     Its lax enough to all for wrong spellings...  ie   internalised will also work.  

f  for fc is ok
i for card id,  well,   i suggest    c /cn  for that.  Trying to have that on other lf commands.

**Comment by mwalker33** [comment]
Yep, sounds good.
In then sample I added to post 1, as is I was matching the first character (as that's all that's needed (atm)
So lf keri clone t     or lf keri clone type  will be the same
That also extends for the rest
e.g. lf keri clone type ms fc 6 etc...…

I have also left the original format, as I did not want to break something without warning.
I will update the ID to CardID

**Comment by iceman1001** [comment]
Done
