### ISSUE TITLE
[idea]The simulation of incoming pull repeat

### ISSUE THREAD

**Issue by Windslab** [RfidResearchGroup/proxmark3#700]
Will be cool to have chance to repeat transaction of custom software when PM in simulation mode and has simulate an eml.

Mb I have lost and don't know some. The people not talkative that's not good.

**Comment by iceman1001** [comment]
Its really hard to figure out what this issues is about since google translate makes strange sentences.

1. This is not the forum.
2. if its a bug,  specifiy details about the bug,  how to recreate the bug.
3. if its a feature request,  specify details about expected feature,  how is should work and why it should be added to the repo.  

 Open source repos doesn't have paid developers working on them. Most people do this voluntary on their spare time.  Its not a wishlist nor a customer support place. This means they spend their time doing enhancing things they want to see.   So I suggest you start learn how to code yourself and then when you ready, make a Pull Request.   

Its an open source project, so feel free to contribute.
