### ISSUE TITLE
command history not save when ctrl-c exiting client

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#781]
**Describe the bug**
When you press ctrl-c to exit / interupt the client (it happens)  the command history isn't saved.
So you loose the commands you tried. 

**To Reproduce**
1. enter client.,
2. run a command you didn't have in your history.  
3. press ctrl-c 
4. enter client again
5. up arrow,  doesn't show the command you ran.

**Expected behavior**
I expect the client to save the history after each run?

**Desktop (please complete the following information):**
latest source from repo.

**Comment by doegox** [comment]
we should be able to trap the ctrl-c and save before exit
I would avoid writing the file at each cmd

**Comment by doegox** [comment]
```c
#include <signal.h>
#include <stdlib.h>

void intHandler(int) {
    savehist...;
}

int main(int argc, char *argv[]) {
    struct sigaction act;
    act.sa_handler = intHandler;
    sigaction(SIGINT, &act, NULL);
...
}
```

**Comment by doegox** [comment]
this might help https://stackoverflow.com/a/34675886

**Comment by iceman1001** [comment]
if you do,  you loose  ctrl-r ,  ctrl-u   etc...

**Comment by iceman1001** [comment]
yeah,  Dunno if I remember it correct,  but I looked into this too a year ago,
and I think I needed to guard the calls for signal handling and for the log history which is readline related.

**Comment by doegox** [comment]
What is the status exactly today ?
On Linux it seems to always save the history properly on ctrl-c. I seldom encountered history files saved with corrupted filenames in the current workdir (but never managed to reproduce it when I wanted), that's why I pushed now a history_path=NULL to avoid to be used after free.
On Windows (PS) the signal handling code is commented.
